blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/ispolkom/node/security/advisories/new
    about: Please do not report vulnerabilities in public issues.
